### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by JumpOff7667** [n1gh7man/simplekernel_hi6210sft#2]
Hi kosmitchak, I appreciate your work on EMUI 4.0.
However, when I try to build kernel, I get sub-make error 2 on line 137 (or 138) of Makefile, I couldn't identify the issue.

Is this a dependency problem?
I tried to build it outside the kernel root folder, I got the same error but in another line of Makefile.

Any Ideas?

OS: kali linux 2017.3 (debian)

**Comment by n1gh7man** [comment]
How you are trying to compile kernel? Always use my build script in the root folder of kernel source.
Anyway try this:
cd pathtokernelhere
./build.sh

**Comment by JumpOff7667** [comment]
Hi, Thanks for replying,
I've been using your script since the beginning and It won't work, even when I write the commands in a terminal console.

I also tried compiling on another OS using virtual machine on Ubuntu 16.4, I get the same error.
Here is more details about the error:

`CC      kernel/elfcore.o`
`CC      kernel/irq_work.o`
`CC      kernel/cpu_pm.o`
`BC      kernel/timeconst.h`
`CHK     kernel/config_data.h`
`UPD     kernel/config_data.h`
`CC      kernel/configs.o`
`CC      kernel/time.o`
`LD      kernel/built-in.o`
`Makefile:137: recipe for target 'sub-make' failed`
`make: *** [sub-make] Error 2`
`Kernel build failed! `

I added in attachment the full output:
[report.txt](https://github.com/kosmitchak/simplekernel_hi6210sft/files/1649719/report.txt)

Can this be related to my processor? I have an Intel Pentium N3540.

**Comment by n1gh7man** [comment]
aarch64-linux-android-ar: error while loading shared libraries: /usr/lib/x86_64-linux-gnu/libfl.so.2: invalid ELF header

That's why
Please see this:
https://forum.xda-developers.com/nexus-4/general/qa-kernel-hells-core-kitkat-b45-stable-t2495373/page959

**Comment by JumpOff7667** [comment]
I followed the instructions on the given link and now it compiles correctly.
Thank you.
